/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyRouteImport } from './routes/why'
import { Route as TwinRouteImport } from './routes/twin'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CustomerZeroRouteImport } from './routes/customer-zero'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsSalesOpsRouteImport } from './routes/solutions.sales-ops'
import { Route as SolutionsPersonalSpaceRouteImport } from './routes/solutions.personal-space'
import { Route as SolutionsFinanceOpsRouteImport } from './routes/solutions.finance-ops'
import { Route as SolutionsByRoleRouteImport } from './routes/solutions.by-role'
import { Route as SolutionsByIndustryRouteImport } from './routes/solutions.by-industry'
import { Route as SolutionsBusinessOpsRouteImport } from './routes/solutions.business-ops'
import { Route as SolutionsAccountSuccessRouteImport } from './routes/solutions.account-success'
import { Route as ProductWorkbenchRouteImport } from './routes/product.workbench'
import { Route as ProductTheTwinRouteImport } from './routes/product.the-twin'
import { Route as ProductReferenceLayerRouteImport } from './routes/product.reference-layer'
import { Route as ProductHowItWorksRouteImport } from './routes/product.how-it-works'
import { Route as ProductApprovalRouteImport } from './routes/product.approval'
import { Route as PlatformTheSpineRouteImport } from './routes/platform.the-spine'
import { Route as PlatformSecurityRouteImport } from './routes/platform.security'
import { Route as PlatformIntegrationsRouteImport } from './routes/platform.integrations'
import { Route as PlatformInfrastructureRouteImport } from './routes/platform.infrastructure'
import { Route as PlatformHowItWorksRouteImport } from './routes/platform.how-it-works'
import { Route as SolutionsByIndustryIndustryRouteImport } from './routes/solutions.by-industry.$industry'

const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerZeroRoute = CustomerZeroRouteImport.update({
  id: '/customer-zero',
  path: '/customer-zero',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSalesOpsRoute = SolutionsSalesOpsRouteImport.update({
  id: '/sales-ops',
  path: '/sales-ops',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsPersonalSpaceRoute = SolutionsPersonalSpaceRouteImport.update({
  id: '/personal-space',
  path: '/personal-space',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsFinanceOpsRoute = SolutionsFinanceOpsRouteImport.update({
  id: '/finance-ops',
  path: '/finance-ops',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsByRoleRoute = SolutionsByRoleRouteImport.update({
  id: '/by-role',
  path: '/by-role',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsByIndustryRoute = SolutionsByIndustryRouteImport.update({
  id: '/by-industry',
  path: '/by-industry',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsBusinessOpsRoute = SolutionsBusinessOpsRouteImport.update({
  id: '/business-ops',
  path: '/business-ops',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsAccountSuccessRoute = SolutionsAccountSuccessRouteImport.update({
  id: '/account-success',
  path: '/account-success',
  getParentRoute: () => SolutionsRoute,
} as any)
const ProductWorkbenchRoute = ProductWorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => ProductRoute,
} as any)
const ProductTheTwinRoute = ProductTheTwinRouteImport.update({
  id: '/the-twin',
  path: '/the-twin',
  getParentRoute: () => ProductRoute,
} as any)
const ProductReferenceLayerRoute = ProductReferenceLayerRouteImport.update({
  id: '/reference-layer',
  path: '/reference-layer',
  getParentRoute: () => ProductRoute,
} as any)
const ProductHowItWorksRoute = ProductHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => ProductRoute,
} as any)
const ProductApprovalRoute = ProductApprovalRouteImport.update({
  id: '/approval',
  path: '/approval',
  getParentRoute: () => ProductRoute,
} as any)
const PlatformTheSpineRoute = PlatformTheSpineRouteImport.update({
  id: '/the-spine',
  path: '/the-spine',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSecurityRoute = PlatformSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformIntegrationsRoute = PlatformIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformInfrastructureRoute = PlatformInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformHowItWorksRoute = PlatformHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => PlatformRoute,
} as any)
const SolutionsByIndustryIndustryRoute =
  SolutionsByIndustryIndustryRouteImport.update({
    id: '/$industry',
    path: '/$industry',
    getParentRoute: () => SolutionsByIndustryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/changelog': typeof ChangelogRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/customer-zero': typeof CustomerZeroRoute
  '/docs': typeof DocsRoute
  '/manifesto': typeof ManifestoRoute
  '/platform': typeof PlatformRouteWithChildren
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/twin': typeof TwinRoute
  '/why': typeof WhyRoute
  '/platform/how-it-works': typeof PlatformHowItWorksRoute
  '/platform/infrastructure': typeof PlatformInfrastructureRoute
  '/platform/integrations': typeof PlatformIntegrationsRoute
  '/platform/security': typeof PlatformSecurityRoute
  '/platform/the-spine': typeof PlatformTheSpineRoute
  '/product/approval': typeof ProductApprovalRoute
  '/product/how-it-works': typeof ProductHowItWorksRoute
  '/product/reference-layer': typeof ProductReferenceLayerRoute
  '/product/the-twin': typeof ProductTheTwinRoute
  '/product/workbench': typeof ProductWorkbenchRoute
  '/solutions/account-success': typeof SolutionsAccountSuccessRoute
  '/solutions/business-ops': typeof SolutionsBusinessOpsRoute
  '/solutions/by-industry': typeof SolutionsByIndustryRouteWithChildren
  '/solutions/by-role': typeof SolutionsByRoleRoute
  '/solutions/finance-ops': typeof SolutionsFinanceOpsRoute
  '/solutions/personal-space': typeof SolutionsPersonalSpaceRoute
  '/solutions/sales-ops': typeof SolutionsSalesOpsRoute
  '/solutions/by-industry/$industry': typeof SolutionsByIndustryIndustryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/changelog': typeof ChangelogRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/customer-zero': typeof CustomerZeroRoute
  '/docs': typeof DocsRoute
  '/manifesto': typeof ManifestoRoute
  '/platform': typeof PlatformRouteWithChildren
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/twin': typeof TwinRoute
  '/why': typeof WhyRoute
  '/platform/how-it-works': typeof PlatformHowItWorksRoute
  '/platform/infrastructure': typeof PlatformInfrastructureRoute
  '/platform/integrations': typeof PlatformIntegrationsRoute
  '/platform/security': typeof PlatformSecurityRoute
  '/platform/the-spine': typeof PlatformTheSpineRoute
  '/product/approval': typeof ProductApprovalRoute
  '/product/how-it-works': typeof ProductHowItWorksRoute
  '/product/reference-layer': typeof ProductReferenceLayerRoute
  '/product/the-twin': typeof ProductTheTwinRoute
  '/product/workbench': typeof ProductWorkbenchRoute
  '/solutions/account-success': typeof SolutionsAccountSuccessRoute
  '/solutions/business-ops': typeof SolutionsBusinessOpsRoute
  '/solutions/by-industry': typeof SolutionsByIndustryRouteWithChildren
  '/solutions/by-role': typeof SolutionsByRoleRoute
  '/solutions/finance-ops': typeof SolutionsFinanceOpsRoute
  '/solutions/personal-space': typeof SolutionsPersonalSpaceRoute
  '/solutions/sales-ops': typeof SolutionsSalesOpsRoute
  '/solutions/by-industry/$industry': typeof SolutionsByIndustryIndustryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/changelog': typeof ChangelogRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/customer-zero': typeof CustomerZeroRoute
  '/docs': typeof DocsRoute
  '/manifesto': typeof ManifestoRoute
  '/platform': typeof PlatformRouteWithChildren
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/twin': typeof TwinRoute
  '/why': typeof WhyRoute
  '/platform/how-it-works': typeof PlatformHowItWorksRoute
  '/platform/infrastructure': typeof PlatformInfrastructureRoute
  '/platform/integrations': typeof PlatformIntegrationsRoute
  '/platform/security': typeof PlatformSecurityRoute
  '/platform/the-spine': typeof PlatformTheSpineRoute
  '/product/approval': typeof ProductApprovalRoute
  '/product/how-it-works': typeof ProductHowItWorksRoute
  '/product/reference-layer': typeof ProductReferenceLayerRoute
  '/product/the-twin': typeof ProductTheTwinRoute
  '/product/workbench': typeof ProductWorkbenchRoute
  '/solutions/account-success': typeof SolutionsAccountSuccessRoute
  '/solutions/business-ops': typeof SolutionsBusinessOpsRoute
  '/solutions/by-industry': typeof SolutionsByIndustryRouteWithChildren
  '/solutions/by-role': typeof SolutionsByRoleRoute
  '/solutions/finance-ops': typeof SolutionsFinanceOpsRoute
  '/solutions/personal-space': typeof SolutionsPersonalSpaceRoute
  '/solutions/sales-ops': typeof SolutionsSalesOpsRoute
  '/solutions/by-industry/$industry': typeof SolutionsByIndustryIndustryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/changelog'
    | '/company'
    | '/contact'
    | '/customer-zero'
    | '/docs'
    | '/manifesto'
    | '/platform'
    | '/pricing'
    | '/product'
    | '/resources'
    | '/solutions'
    | '/twin'
    | '/why'
    | '/platform/how-it-works'
    | '/platform/infrastructure'
    | '/platform/integrations'
    | '/platform/security'
    | '/platform/the-spine'
    | '/product/approval'
    | '/product/how-it-works'
    | '/product/reference-layer'
    | '/product/the-twin'
    | '/product/workbench'
    | '/solutions/account-success'
    | '/solutions/business-ops'
    | '/solutions/by-industry'
    | '/solutions/by-role'
    | '/solutions/finance-ops'
    | '/solutions/personal-space'
    | '/solutions/sales-ops'
    | '/solutions/by-industry/$industry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/changelog'
    | '/company'
    | '/contact'
    | '/customer-zero'
    | '/docs'
    | '/manifesto'
    | '/platform'
    | '/pricing'
    | '/product'
    | '/resources'
    | '/solutions'
    | '/twin'
    | '/why'
    | '/platform/how-it-works'
    | '/platform/infrastructure'
    | '/platform/integrations'
    | '/platform/security'
    | '/platform/the-spine'
    | '/product/approval'
    | '/product/how-it-works'
    | '/product/reference-layer'
    | '/product/the-twin'
    | '/product/workbench'
    | '/solutions/account-success'
    | '/solutions/business-ops'
    | '/solutions/by-industry'
    | '/solutions/by-role'
    | '/solutions/finance-ops'
    | '/solutions/personal-space'
    | '/solutions/sales-ops'
    | '/solutions/by-industry/$industry'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/changelog'
    | '/company'
    | '/contact'
    | '/customer-zero'
    | '/docs'
    | '/manifesto'
    | '/platform'
    | '/pricing'
    | '/product'
    | '/resources'
    | '/solutions'
    | '/twin'
    | '/why'
    | '/platform/how-it-works'
    | '/platform/infrastructure'
    | '/platform/integrations'
    | '/platform/security'
    | '/platform/the-spine'
    | '/product/approval'
    | '/product/how-it-works'
    | '/product/reference-layer'
    | '/product/the-twin'
    | '/product/workbench'
    | '/solutions/account-success'
    | '/solutions/business-ops'
    | '/solutions/by-industry'
    | '/solutions/by-role'
    | '/solutions/finance-ops'
    | '/solutions/personal-space'
    | '/solutions/sales-ops'
    | '/solutions/by-industry/$industry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ChangelogRoute: typeof ChangelogRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  CustomerZeroRoute: typeof CustomerZeroRoute
  DocsRoute: typeof DocsRoute
  ManifestoRoute: typeof ManifestoRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRouteWithChildren
  ResourcesRoute: typeof ResourcesRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  TwinRoute: typeof TwinRoute
  WhyRoute: typeof WhyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-zero': {
      id: '/customer-zero'
      path: '/customer-zero'
      fullPath: '/customer-zero'
      preLoaderRoute: typeof CustomerZeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/sales-ops': {
      id: '/solutions/sales-ops'
      path: '/sales-ops'
      fullPath: '/solutions/sales-ops'
      preLoaderRoute: typeof SolutionsSalesOpsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/personal-space': {
      id: '/solutions/personal-space'
      path: '/personal-space'
      fullPath: '/solutions/personal-space'
      preLoaderRoute: typeof SolutionsPersonalSpaceRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/finance-ops': {
      id: '/solutions/finance-ops'
      path: '/finance-ops'
      fullPath: '/solutions/finance-ops'
      preLoaderRoute: typeof SolutionsFinanceOpsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/by-role': {
      id: '/solutions/by-role'
      path: '/by-role'
      fullPath: '/solutions/by-role'
      preLoaderRoute: typeof SolutionsByRoleRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/by-industry': {
      id: '/solutions/by-industry'
      path: '/by-industry'
      fullPath: '/solutions/by-industry'
      preLoaderRoute: typeof SolutionsByIndustryRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/business-ops': {
      id: '/solutions/business-ops'
      path: '/business-ops'
      fullPath: '/solutions/business-ops'
      preLoaderRoute: typeof SolutionsBusinessOpsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/account-success': {
      id: '/solutions/account-success'
      path: '/account-success'
      fullPath: '/solutions/account-success'
      preLoaderRoute: typeof SolutionsAccountSuccessRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/product/workbench': {
      id: '/product/workbench'
      path: '/workbench'
      fullPath: '/product/workbench'
      preLoaderRoute: typeof ProductWorkbenchRouteImport
      parentRoute: typeof ProductRoute
    }
    '/product/the-twin': {
      id: '/product/the-twin'
      path: '/the-twin'
      fullPath: '/product/the-twin'
      preLoaderRoute: typeof ProductTheTwinRouteImport
      parentRoute: typeof ProductRoute
    }
    '/product/reference-layer': {
      id: '/product/reference-layer'
      path: '/reference-layer'
      fullPath: '/product/reference-layer'
      preLoaderRoute: typeof ProductReferenceLayerRouteImport
      parentRoute: typeof ProductRoute
    }
    '/product/how-it-works': {
      id: '/product/how-it-works'
      path: '/how-it-works'
      fullPath: '/product/how-it-works'
      preLoaderRoute: typeof ProductHowItWorksRouteImport
      parentRoute: typeof ProductRoute
    }
    '/product/approval': {
      id: '/product/approval'
      path: '/approval'
      fullPath: '/product/approval'
      preLoaderRoute: typeof ProductApprovalRouteImport
      parentRoute: typeof ProductRoute
    }
    '/platform/the-spine': {
      id: '/platform/the-spine'
      path: '/the-spine'
      fullPath: '/platform/the-spine'
      preLoaderRoute: typeof PlatformTheSpineRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/security': {
      id: '/platform/security'
      path: '/security'
      fullPath: '/platform/security'
      preLoaderRoute: typeof PlatformSecurityRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/integrations': {
      id: '/platform/integrations'
      path: '/integrations'
      fullPath: '/platform/integrations'
      preLoaderRoute: typeof PlatformIntegrationsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/infrastructure': {
      id: '/platform/infrastructure'
      path: '/infrastructure'
      fullPath: '/platform/infrastructure'
      preLoaderRoute: typeof PlatformInfrastructureRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/how-it-works': {
      id: '/platform/how-it-works'
      path: '/how-it-works'
      fullPath: '/platform/how-it-works'
      preLoaderRoute: typeof PlatformHowItWorksRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/solutions/by-industry/$industry': {
      id: '/solutions/by-industry/$industry'
      path: '/$industry'
      fullPath: '/solutions/by-industry/$industry'
      preLoaderRoute: typeof SolutionsByIndustryIndustryRouteImport
      parentRoute: typeof SolutionsByIndustryRoute
    }
  }
}

interface PlatformRouteChildren {
  PlatformHowItWorksRoute: typeof PlatformHowItWorksRoute
  PlatformInfrastructureRoute: typeof PlatformInfrastructureRoute
  PlatformIntegrationsRoute: typeof PlatformIntegrationsRoute
  PlatformSecurityRoute: typeof PlatformSecurityRoute
  PlatformTheSpineRoute: typeof PlatformTheSpineRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformHowItWorksRoute: PlatformHowItWorksRoute,
  PlatformInfrastructureRoute: PlatformInfrastructureRoute,
  PlatformIntegrationsRoute: PlatformIntegrationsRoute,
  PlatformSecurityRoute: PlatformSecurityRoute,
  PlatformTheSpineRoute: PlatformTheSpineRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

interface ProductRouteChildren {
  ProductApprovalRoute: typeof ProductApprovalRoute
  ProductHowItWorksRoute: typeof ProductHowItWorksRoute
  ProductReferenceLayerRoute: typeof ProductReferenceLayerRoute
  ProductTheTwinRoute: typeof ProductTheTwinRoute
  ProductWorkbenchRoute: typeof ProductWorkbenchRoute
}

const ProductRouteChildren: ProductRouteChildren = {
  ProductApprovalRoute: ProductApprovalRoute,
  ProductHowItWorksRoute: ProductHowItWorksRoute,
  ProductReferenceLayerRoute: ProductReferenceLayerRoute,
  ProductTheTwinRoute: ProductTheTwinRoute,
  ProductWorkbenchRoute: ProductWorkbenchRoute,
}

const ProductRouteWithChildren =
  ProductRoute._addFileChildren(ProductRouteChildren)

interface SolutionsByIndustryRouteChildren {
  SolutionsByIndustryIndustryRoute: typeof SolutionsByIndustryIndustryRoute
}

const SolutionsByIndustryRouteChildren: SolutionsByIndustryRouteChildren = {
  SolutionsByIndustryIndustryRoute: SolutionsByIndustryIndustryRoute,
}

const SolutionsByIndustryRouteWithChildren =
  SolutionsByIndustryRoute._addFileChildren(SolutionsByIndustryRouteChildren)

interface SolutionsRouteChildren {
  SolutionsAccountSuccessRoute: typeof SolutionsAccountSuccessRoute
  SolutionsBusinessOpsRoute: typeof SolutionsBusinessOpsRoute
  SolutionsByIndustryRoute: typeof SolutionsByIndustryRouteWithChildren
  SolutionsByRoleRoute: typeof SolutionsByRoleRoute
  SolutionsFinanceOpsRoute: typeof SolutionsFinanceOpsRoute
  SolutionsPersonalSpaceRoute: typeof SolutionsPersonalSpaceRoute
  SolutionsSalesOpsRoute: typeof SolutionsSalesOpsRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsAccountSuccessRoute: SolutionsAccountSuccessRoute,
  SolutionsBusinessOpsRoute: SolutionsBusinessOpsRoute,
  SolutionsByIndustryRoute: SolutionsByIndustryRouteWithChildren,
  SolutionsByRoleRoute: SolutionsByRoleRoute,
  SolutionsFinanceOpsRoute: SolutionsFinanceOpsRoute,
  SolutionsPersonalSpaceRoute: SolutionsPersonalSpaceRoute,
  SolutionsSalesOpsRoute: SolutionsSalesOpsRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ChangelogRoute: ChangelogRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  CustomerZeroRoute: CustomerZeroRoute,
  DocsRoute: DocsRoute,
  ManifestoRoute: ManifestoRoute,
  PlatformRoute: PlatformRouteWithChildren,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRouteWithChildren,
  ResourcesRoute: ResourcesRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  TwinRoute: TwinRoute,
  WhyRoute: WhyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
